#!/bin/sh

union()
{
	cat -
	"$@"
}

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"
history="$cachedir/dmenu_history"

selection=$( (tac "$history" | awk '!a[$0]++'; dmenu_path) | dmenu "$@")

if [ -n "$selection" ]; then
	echo "$selection" >> "$history"
	echo "$selection" | ${SHELL:-"/bin/sh"} &
fi
